# Generated by Django 2.0.1 on 2018-01-12 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='sex',
            new_name='gender',
        ),
    ]
